import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  DB_HOST: Joi.string().default('localhost'),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_EXPIRATION: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRATION: Joi.string().default('7d'),
  CONFIRMATION_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  PASSWORD_RESET_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  MAIL_HOST: Joi.string().default('mailpit'),
  MAIL_PORT: Joi.number().default(1025),
  MAIL_FROM: Joi.string().default('"StreamTube" <noreply@streamtube.com>'),
  SWAGGER_ENABLED: Joi.string().valid('true', 'false').default('false'),
  REDIS_HOST: Joi.string().default('redis'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_URL: Joi.string().default('redis://redis:6379'),
  MINIO_ENDPOINT: Joi.string().uri().default('http://minio:9000'),
  MINIO_REGION: Joi.string().default('us-east-1'),
  MINIO_BUCKET: Joi.string().default('streamtube'),
  MINIO_ACCESS_KEY: Joi.string().default('streamtube'),
  MINIO_SECRET_KEY: Joi.string().default('streamtube'),
  MINIO_PUBLIC_URL: Joi.string().uri().default('http://localhost:9000'),
  MINIO_UPLOAD_PART_SIZE: Joi.number().default(5 * 1024 * 1024),
  MINIO_PRESIGNED_EXPIRES_IN_SECONDS: Joi.number().default(3600),
  MAX_VIDEO_SIZE_BYTES: Joi.number().default(10 * 1024 * 1024 * 1024),
  VIDEO_QUEUE_NAME: Joi.string().default('video-processing'),
  VIDEO_WORKER_CONCURRENCY: Joi.number().default(2),
  VIDEO_PROCESSING_TIMEOUT_SECONDS: Joi.number().default(600),
});
